Fix the framework picker for form
TanStack/tanstack.com pull request #133
Opened 2024-01-01 13:10 UTC by fulopkovacs

Two issues has been fixed for the framework picker of the Form project:
1. It was not working on core pages, like Overview, which is the first page the users see when they open the docs (I thought that the framework picker is not working at all because of this for a long time).
2. If the user selected a framework and then viewed a core doc page, it went back to React, regardless of the previously selected framework.

2024-01-01 13:20 UTC, fulopkovacs commented
@crutchcorn There are a couple of ideas, that that we could add to this PR:

1. Make these changes for `Store` too (at first glance, the structure of `Form` and `Store` look very similar)

2. Drop the `framework` string from the routes of the docs pages:
   - `"/docs/latest/framework/react/quick-start"` -> `"/docs/latest/react/quick-start"`
   - this would make the docs more consistent (the `Query` doc routes already look like this)
   - I think it's technically feasible, because we know all the names of the frameworks from the `config.json` file in the project's repo (I haven't thought deeply about this problem yet though)
  
  Ofc these are just suggestions, changing routes are scary, plus I know much less about the projects than you do. 🤣 Wdyt?

2024-01-01 16:17 UTC, crutchcorn commented
@fulopkovacs let's do #1 for sure. I'm less sure about #2 - @tannerlinsley what do you think?

2024-01-01 18:35 UTC, fulopkovacs commented on app/routes/store.$version.docs.framework.$framework.examples._index.tsx
I think `examples` wasn't supposed to be a dynamic segment in this route, because `store.$version.docs.framework.$framework.$examples._index.tsx` matches `/store/latest/docs/framework/react/quick-start` (`$examples`: `"quick-start"`) and all the other framework-related doc pages.

2024-01-01 18:45 UTC, fulopkovacs commented on app/routes/form.$version.docs.framework.$framework.$.tsx
>  export const loader = async (context: LoaderFunctionArgs) => {
The body of the `loader` function is basically identical in this file and [`app/routes/store.$version.docs.framework.$framework.$.tsx`](https://github.com/TanStack/tanstack.com/pull/133/files#diff-cec2d983f6a6adc45d30d2ffe186f539471e0d67e4948e2c3e2b8b5ed15276caR11-R55). If we want to follow the DRY practices, we can extract the shared logic to a helper function.

2024-01-11 19:34 UTC, crutchcorn requested changes
@fulopkovacs I noticed that we've seemingly fixed this by making the `core` docs duplicate through every framework.

```
core/quick-start.md -> routes/react/quick-start.md, routes/vue/quick-start.md, etc
```

This is a clever solution, but unfortunately one we can't move forward with. That would break our doc's SEO pretty bad, as there wouldn't be a canonical URL for `core` docs anymore

Instead, let's use some other kind of tool (maybe localstorage + a sidebar refactor?) to solve this issue.

2024-01-11 22:10 UTC, fulopkovacs commented
> @fulopkovacs I noticed that we've seemingly fixed this by making the `core` docs duplicate through every framework.
> 
> ```
> core/quick-start.md -> routes/react/quick-start.md, routes/vue/quick-start.md, etc
> ```
>
> This is a clever solution, but unfortunately one we can't move forward with. That would break our doc's SEO pretty bad, as there wouldn't be a canonical URL for `core` docs anymore
> 
> Instead, let's use some other kind of tool (maybe localstorage + a sidebar refactor?) to solve this 

Sure, I can explore other options. We can use `URLSearchParams` if we want to keep using SSR, or go down the client-first `localStorage` route, I'll check which one requires less changes!

2024-01-11 22:11 UTC, crutchcorn commented
You're awesome, thank you for your help and receptiveness to feedback. Keep up the amazing work! 🔥

2024-01-11 22:54 UTC, fulopkovacs commented
Ok, I went with `localStorage` for cleaner URLs. It's pretty late here, so this implementation might have mistakes, idk... I'll review it tomorrow and request a review from you when I'm ready!

2024-01-12 22:07 UTC, fulopkovacs commented on app/routes/form.$version.docs.$.tsx
> +export const meta: MetaFunction<typeof loader> = ({ data }) => {
I fixed the type errors around the `meta` functions in the files I worked on. Most of the remaining errors of this kind are getting fixed in https://github.com/TanStack/tanstack.com/pull/135.

2024-01-12 22:28 UTC, fulopkovacs commented on app/routes/store.$version.docs.framework.$framework.examples._index.tsx
This fixes https://github.com/TanStack/tanstack.com/issues/129#issuecomment-1890062946

2024-01-13 05:00 UTC, crutchcorn requested changes

2024-01-13 05:00 UTC, crutchcorn commented on app/routes/store.$version.docs.framework.$framework.examples._index.tsx
This is awesome, thank you!

2024-01-13 05:00 UTC, crutchcorn commented on app/routes/store.tsx
> +    params.framework || localStorage.getItem(storeLocalStorageKey) || 'react'
Just checking on this again - could we keep it as `framework` rather than `framework-store` and `framework-form`?

2024-01-13 14:02 UTC, fulopkovacs commented on app/routes/form.tsx
> +    params.framework || localStorage.getItem(formLocalStorageKey) || 'react'
Yeah, no specific reason. I just assumed it's not a feature but a bug! I'm changing it back to `framework`.

2024-01-15 22:45 UTC, crutchcorn approved these changes
This is a great fix, good work!

2024-01-15 22:46 UTC, merged